# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A blockwise loop-based Rcpp implementation for computing \eqn{x'Ay}
#'
#' This function computes \eqn{x'Ay} using blockwise nested loop using Rcpp
#' @param x A size \eqn{n} vector
#' @param y A size \eqn{m} vector
#' @param A A size (\eqn{n x m}) matrix
#' @param blkSize The size of blocks (in #rows or #cols) in calculating \eqn{x'Ay}
#' @return A scalar value evaluating \eqn{x'Ay}
#' @examples
#' quadsumB(rep(1,100),rep(1,100),matrix(1,100,100), 100)  # [1] 10000
quadsumB <- function(x, y, A, blkSize) {
    .Call(`_quadsum815_quadsumB`, x, y, A, blkSize)
}

#' A loop-based Rcpp implementation for computing \eqn{x'Ay}
#'
#' @param x A size \eqn{n} vector
#' @param y A size \eqn{m} vector
#' @param A A size (\eqn{n x m}) matrix
#' @return A scalar value evaluating \eqn{x'Ay}
#' @examples
#' quadsumC(rep(1,100),rep(1,100),matrix(1,100,100))  # [1] 10000
quadsumC <- function(x, y, A) {
    .Call(`_quadsum815_quadsumC`, x, y, A)
}

